name: Project-AI service Deploy

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} '
            sudo su - <<EOF
            cd ${{ secrets.PROJECT_PATH }} &&
            source enve/bin/activate &&
            cd project-ai &&
            git config --global --add safe.directory $PWD &&
            git pull origin main &&
            pip install -r requirements.txt &&
            pm2 restart agent-api
          ' 